travis:
  secure:
    BINSTAR_TOKEN: aGuF/EIICFWypmn+k88l/RE4TyspMMJPme9yRJ2I0F7CgduwDAS1J5oqgXfpLWbAHXW+Wl2D8T4kZG9zFhsgps523XIcelQupDbXV5aQgGeu/of4608tzwfTw9s4Zn3vuyMP2xn34ywA5MDbq5WuHk3XEdyvdLPizgXVVLsbbbvTTiv8VK69VajtVqMhdUppz/QcooyiMZds4fpCD099QwdaMFZRtROxVDoJRjSr6Mt4ZKAVXhU7dwm22gxtf/GAF/bQbgZc7pF3zSXzVoGvgSJJrICTvcPwbEjkPzBR8sfgJ/1inZzznqGshmRxq54kID65OmyDHvDnQ+R9dtnD1Q2aBmos4DhE00vzt5/nH59eIqXA3x+AiVwUPM5rPhVVwHrhlR3K/Tla8OtyDnroe/rgy5N0qD7u0EBKVrt9hFXZR97wyDQ1ZR4Kca5At6Jp36hneB2AHNMaVldcK/+ELMr4QEyV3U6VTMcGqIlTfIU48H3HmZLCoaGFjKZjTT1OiayHDGg5RM2h6MjdAg33Z7u/lYHiTashEtfIEXklO19qcXV4GZlfXYcmzGt4dHKi8sqTNasVcTBNWFGDCo6NEjFCcf5IAeXi4bZLpPuaGK0RK5ZzXZgMzaWmX3jCuF5lgJBShbHUIgfbWyEk6Stj1QeM02wuZG9iC46Wepc/6X4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
